name: Build/Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      part:
        required: false
        default: ''

jobs:
  build:
    name: Build the library and run tests
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and install library
        run: |
          ./configure --enable-static --enable-shared --enable-debug
          make
          sudo make install

      - name: Run tests
        run: |
          make check
